In [2]:
import pandas as pd
df=pd.read_csv('insuranceinfo1.csv')
df.describe()

          IssuerId2     custnum
count    402.000000  401.000000
mean   59399.798507   14.840399
std    25343.937114    3.854798
min      219.000000   13.000000
25%    40435.000000   13.000000
50%    57451.000000   13.000000
75%    84966.000000   15.000000
max    99787.000000   35.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IssuerId        403 non-null    object
 1   IssuerId2       402 non-null    float64
 2   BusinessDate    402 non-null    object
 3   StateCode       402 non-null    object
 4   SourceName      402 non-null    object
 5   NetworkName     402 non-null    object
 6   NetworkURL      401 non-null    object
 7   custnum         401 non-null    float64
 8   MarketCoverage  18 non-null     object
 9   DentalOnlyPlan  18 non-null     object
dtypes: float64(2), object(8)
memory usage: 31.6+ KB

In [4]:
df.count()

IssuerId          403
IssuerId2         402
BusinessDate      402
StateCode         402
SourceName        402
NetworkName       402
NetworkURL        401
custnum           401
MarketCoverage     18
DentalOnlyPlan     18
dtype: int64

In [7]:
df.isnull().sum()

IssuerId            0
IssuerId2           1
BusinessDate        1
StateCode           1
SourceName          1
NetworkName         1
NetworkURL          2
custnum             2
MarketCoverage    385
DentalOnlyPlan    385
dtype: int64

In [8]:
df.head()

,IssuerId,IssuerId2,BusinessDate,StateCode,SourceName,NetworkName,NetworkURL,custnum,MarketCoverage,DentalOnlyPlan
0,21989,21989.0,2019-10-01,AK,HIOS,ODS Premier,https://www.modahealth.com/ProviderSearch/face...,13.0,NaN,NaN
1,219,219.0,2019-10-01,AK,HIOS,ODS Premier,NaN,NaN,NaN,NaN
2,38344,38344.0,2019-10-01,AK,HIOS,HeritagePlus,https://www.premera.com/wa/visitor/,13.0,NaN,NaN
3,38536,38536.0,2019-10-01,AK,HIOS,Lincoln Dental Connect,http://lfg.go2dental.com/member/dental_search/...,13.0,NaN,NaN
4,42507,42507.0,2019-10-01,AK,HIOS,DentalGuard Preferred,https://www.guardiananytime.com/fpapp/FPWeb/de...,13.0,NaN,NaN

In [9]:
df.tail()

,IssuerId,IssuerId2,BusinessDate,StateCode,SourceName,NetworkName,NetworkURL,custnum,MarketCoverage,DentalOnlyPlan
398,84966,84966.0,2019-10-01,SC,HIOS,EHB Enhanced Dental Plan (High),https://www.metlife.com/dental,14.0,NaN,NaN
399,84966,84966.0,2019-10-01,SC,HIOS,Family Basic Dental Plan (Low),https://www.metlife.com/dental,13.0,NaN,NaN
400,84966,84966.0,2019-10-01,SC,HIOS,Family Enhanced Dental Plan (High),https://www.metlife.com/dental,13.0,NaN,NaN
401,89281,89281.0,2019-10-01,SC,HIOS,DenteMax,http://www2.dentemax.com/,13.0,NaN,NaN
402,footer count is 402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
#remove header
#option 1
#ignore header while reading itself
df = pd.read_csv('insuranceinfo1.csv', skiprows=1)
print(df.head())

#option2
#read header in the data and remove the first row
df=pd.read_csv('insuranceinfo1.csv', header=None)
df=df.iloc[1:]
print("........")
print(df.head())

#option 3 after loading the columsn names drop the column names
#override columns with 0 based column names
df = pd.read_csv('insuranceinfo1.csv')
df.columns=range(len(df.columns))
print("........")
print(df.head())

   21989  21989.1  2019-10-01  AK  HIOS             ODS Premier  \
0    219    219.0  2019-10-01  AK  HIOS             ODS Premier
1  38344  38344.0  2019-10-01  AK  HIOS            HeritagePlus
2  38536  38536.0  2019-10-01  AK  HIOS  Lincoln Dental Connect
3  42507  42507.0  2019-10-01  AK  HIOS   DentalGuard Preferred
4  73836  73836.0  2019-10-01  AK  HIOS   Moda Plus AK Regional

  https://www.modahealth.com/ProviderSearch/faces/webpages/home.xhtml?dn=ods  \
0                                                NaN
1                https://www.premera.com/wa/visitor/
2  http://lfg.go2dental.com/member/dental_search/...
3  https://www.guardiananytime.com/fpapp/FPWeb/de...
4  https://www.modahealth.com/ProviderSearch/face...

     13 Unnamed: 8 Unnamed: 9
0   NaN        NaN        NaN
1  13.0        NaN        NaN
2  13.0        NaN        NaN
3  13.0        NaN        NaN
4  13.0        NaN        NaN
........
       0      1           2   3     4                       5  \
1  21989  21989  2019-10-01  AK  HIOS             ODS Premier
2    219    219  2019-10-01  AK  HIOS             ODS Premier
3  38344  38344  2019-10-01  AK  HIOS            HeritagePlus
4  38536  38536  2019-10-01  AK  HIOS  Lincoln Dental Connect
5  42507  42507  2019-10-01  AK  HIOS   DentalGuard Preferred

                                                   6    7    8    9
1  https://www.modahealth.com/ProviderSearch/face...   13  NaN  NaN
2                                                NaN  NaN  NaN  NaN
3                https://www.premera.com/wa/visitor/   13  NaN  NaN
4  http://lfg.go2dental.com/member/dental_search/...   13  NaN  NaN
5  https://www.guardiananytime.com/fpapp/FPWeb/de...   13  NaN  NaN
........
       0        1           2   3     4                       5  \
0  21989  21989.0  2019-10-01  AK  HIOS             ODS Premier
1    219    219.0  2019-10-01  AK  HIOS             ODS Premier
2  38344  38344.0  2019-10-01  AK  HIOS            HeritagePlus
3  38536  38536.0  2019-10-01  AK  HIOS  Lincoln Dental Connect
4  42507  42507.0  2019-10-01  AK  HIOS   DentalGuard Preferred

                                                   6     7    8    9
0  https://www.modahealth.com/ProviderSearch/face...  13.0  NaN  NaN
1                                                NaN   NaN  NaN  NaN
2                https://www.premera.com/wa/visitor/  13.0  NaN  NaN
3  http://lfg.go2dental.com/member/dental_search/...  13.0  NaN  NaN
4  https://www.guardiananytime.com/fpapp/FPWeb/de...  13.0  NaN  NaN

In [38]:
#remove footer
df=pd.read_csv('insuranceinfo1.csv')
print(df.tail(2))

#option1
print(df.iloc[:len(df)-1].tail())

#option2
print(df.iloc[-1:])

#option3
print(df.drop(df.index[-1]))

#option4
print(df.drop(df.tail(1).index))

                IssuerId  IssuerId2 BusinessDate StateCode SourceName  \
401                89281    89281.0   2019-10-01        SC       HIOS
402  footer count is 402        NaN          NaN       NaN        NaN

    NetworkName                 NetworkURL  custnum MarketCoverage  \
401    DenteMax  http://www2.dentemax.com/     13.0            NaN
402         NaN                        NaN      NaN            NaN

    DentalOnlyPlan
401            NaN
402            NaN
    IssuerId  IssuerId2 BusinessDate StateCode SourceName  \
397    84966    84966.0   2019-10-01        SC       HIOS
398    84966    84966.0   2019-10-01        SC       HIOS
399    84966    84966.0   2019-10-01        SC       HIOS
400    84966    84966.0   2019-10-01        SC       HIOS
401    89281    89281.0   2019-10-01        SC       HIOS

                            NetworkName                      NetworkURL  \
397         EHB Basic Dental Plan (Low)  https://www.metlife.com/dental
398     EHB Enhanced Dental Plan (High)  https://www.metlife.com/dental
399      Family Basic Dental Plan (Low)  https://www.metlife.com/dental
400  Family Enhanced Dental Plan (High)  https://www.metlife.com/dental
401                            DenteMax       http://www2.dentemax.com/

     custnum MarketCoverage DentalOnlyPlan
397     13.0            NaN            NaN
398     14.0            NaN            NaN
399     13.0            NaN            NaN
400     13.0            NaN            NaN
401     13.0            NaN            NaN
                IssuerId  IssuerId2 BusinessDate StateCode SourceName  \
402  footer count is 402        NaN          NaN       NaN        NaN

    NetworkName NetworkURL  custnum MarketCoverage DentalOnlyPlan
402         NaN        NaN      NaN            NaN            NaN
    IssuerId  IssuerId2 BusinessDate StateCode SourceName  \
0      21989    21989.0   2019-10-01        AK       HIOS
1        219      219.0   2019-10-01        AK       HIOS
2      38344    38344.0   2019-10-01        AK       HIOS
3      38536    38536.0   2019-10-01        AK       HIOS
4      42507    42507.0   2019-10-01        AK       HIOS
..       ...        ...          ...       ...        ...
397    84966    84966.0   2019-10-01        SC       HIOS
398    84966    84966.0   2019-10-01        SC       HIOS
399    84966    84966.0   2019-10-01        SC       HIOS
400    84966    84966.0   2019-10-01        SC       HIOS
401    89281    89281.0   2019-10-01        SC       HIOS

                            NetworkName  \
0                           ODS Premier
1                           ODS Premier
2                          HeritagePlus
3                Lincoln Dental Connect
4                 DentalGuard Preferred
..                                  ...
397         EHB Basic Dental Plan (Low)
398     EHB Enhanced Dental Plan (High)
399      Family Basic Dental Plan (Low)
400  Family Enhanced Dental Plan (High)
401                            DenteMax

                                            NetworkURL  custnum  \
0    https://www.modahealth.com/ProviderSearch/face...     13.0
1                                                  NaN      NaN
2                  https://www.premera.com/wa/visitor/     13.0
3    http://lfg.go2dental.com/member/dental_search/...     13.0
4    https://www.guardiananytime.com/fpapp/FPWeb/de...     13.0
..                                                 ...      ...
397                     https://www.metlife.com/dental     13.0
398                     https://www.metlife.com/dental     14.0
399                     https://www.metlife.com/dental     13.0
400                     https://www.metlife.com/dental     13.0
401                          http://www2.dentemax.com/     13.0

    MarketCoverage DentalOnlyPlan
0              NaN            NaN
1              NaN            NaN
2              NaN            NaN
3              NaN            NaN
4              NaN            NaN
..             ...            ...
397            NaN            NaN
398            NaN            NaN
399            NaN            NaN
400            NaN            NaN
401            NaN            NaN

[402 rows x 10 columns]
    IssuerId  IssuerId2 BusinessDate StateCode SourceName  \
0      21989    21989.0   2019-10-01        AK       HIOS
1        219      219.0   2019-10-01        AK       HIOS
2      38344    38344.0   2019-10-01        AK       HIOS
3      38536    38536.0   2019-10-01        AK       HIOS
4      42507    42507.0   2019-10-01        AK       HIOS
..       ...        ...          ...       ...        ...
397    84966    84966.0   2019-10-01        SC       HIOS
398    84966    84966.0   2019-10-01        SC       HIOS
399    84966    84966.0   2019-10-01        SC       HIOS
400    84966    84966.0   2019-10-01        SC       HIOS
401    89281    89281.0   2019-10-01        SC       HIOS

                            NetworkName  \
0                           ODS Premier
1                           ODS Premier
2                          HeritagePlus
3                Lincoln Dental Connect
4                 DentalGuard Preferred
..                                  ...
397         EHB Basic Dental Plan (Low)
398     EHB Enhanced Dental Plan (High)
399      Family Basic Dental Plan (Low)
400  Family Enhanced Dental Plan (High)
401                            DenteMax

                                            NetworkURL  custnum  \
0    https://www.modahealth.com/ProviderSearch/face...     13.0
1                                                  NaN      NaN
2                  https://www.premera.com/wa/visitor/     13.0
3    http://lfg.go2dental.com/member/dental_search/...     13.0
4    https://www.guardiananytime.com/fpapp/FPWeb/de...     13.0
..                                                 ...      ...
397                     https://www.metlife.com/dental     13.0
398                     https://www.metlife.com/dental     14.0
399                     https://www.metlife.com/dental     13.0
400                     https://www.metlife.com/dental     13.0
401                          http://www2.dentemax.com/     13.0

    MarketCoverage DentalOnlyPlan
0              NaN            NaN
1              NaN            NaN
2              NaN            NaN
3              NaN            NaN
4              NaN            NaN
..             ...            ...
397            NaN            NaN
398            NaN            NaN
399            NaN            NaN
400            NaN            NaN
401            NaN            NaN

[402 rows x 10 columns]

In [62]:
df=pd.read_csv('insuranceinfo3.csv', header=None)
df=df.drop(df.head(1).index)
df=df.drop(df.tail(1).index)
df.index=range(len(df)) #reset the index starting to 0
#print(df.head())
#print(df.tail(2))

#to print empty records
print(df[df.isnull().all(axis=1)])

#to remove empty records
print(df.dropna(how='all').head())

      0    1    2    3    4    5    6    7    8    9
3   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
35  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
       0      1           2   3     4                       5  \
0  21989  21989  2019-10-01  AK  HIOS             ODS Premier
1    219    219  2019-10-01  AK  HIOS             ODS Premier
2  38344  38344  2019-10-01  AK  HIOS            HeritagePlus
4  38536  38536  2019-10-01  AK  HIOS  Lincoln Dental Connect
5  42507  42507  2019-10-01  AK  HIOS   DentalGuard Preferred

                                                   6    7    8    9
0  https://www.modahealth.com/ProviderSearch/face...   13  NaN  NaN
1                                                NaN  NaN  NaN  NaN
2                https://www.premera.com/wa/visitor/   13  NaN  NaN
4  http://lfg.go2dental.com/member/dental_search/...   13  NaN  NaN
5  https://www.guardiananytime.com/fpapp/FPWeb/de...   13  NaN  NaN

In [84]:
df=pd.read_csv('insuranceinfo4.csv')
#print(df.head())
#print(df.info())
df.columns=['col1']
#print(df.columns)
#print(df.head())
df=df['col1'].str.split("*", expand=True)
print(df.head())

       0      1           2     3     4                       5  \
0  21989  21989  2019-10-01    AK  HIOS             ODS Premier
1    219    219  2019-10-01    AK  HIOS             ODS Premier
2  38344  38344  2019-10-01    AK  HIOS            HeritagePlus
3                            None  None                    None
4  38536  38536  2019-10-01    AK  HIOS  Lincoln Dental Connect

                                                   6     7     8     9
0  https://www.modahealth.com/ProviderSearch/face...    13
1                                               None  None  None  None
2                https://www.premera.com/wa/visitor/    13
3                                               None  None  None  None
4  http://lfg.go2dental.com/member/dental_search/...    13

In [95]:
df=pd.read_csv('insuranceinfo1.csv')
df.info()
df1=df.dropna()
df1.info()

#row that are dropped
df2=df[df.isnull().any(axis=1)]
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IssuerId        403 non-null    object
 1   IssuerId2       402 non-null    float64
 2   BusinessDate    402 non-null    object
 3   StateCode       402 non-null    object
 4   SourceName      402 non-null    object
 5   NetworkName     402 non-null    object
 6   NetworkURL      401 non-null    object
 7   custnum         401 non-null    float64
 8   MarketCoverage  18 non-null     object
 9   DentalOnlyPlan  18 non-null     object
dtypes: float64(2), object(8)
memory usage: 31.6+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 260 to 277
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IssuerId        18 non-null     object
 1   IssuerId2       18 non-null     float64
 2   BusinessDate    18 non-null     object
 3   StateCode       18 non-null     object
 4   SourceName      18 non-null     object
 5   NetworkName     18 non-null     object
 6   NetworkURL      18 non-null     object
 7   custnum         18 non-null     float64
 8   MarketCoverage  18 non-null     object
 9   DentalOnlyPlan  18 non-null     object
dtypes: float64(2), object(8)
memory usage: 1.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 385 entries, 0 to 402
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IssuerId        385 non-null    object
 1   IssuerId2       384 non-null    float64
 2   BusinessDate    384 non-null    object
 3   StateCode       384 non-null    object
 4   SourceName      384 non-null    object
 5   NetworkName     384 non-null    object
 6   NetworkURL      383 non-null    object
 7   custnum         383 non-null    float64
 8   MarketCoverage  0 non-null      object
 9   DentalOnlyPlan  0 non-null      object
dtypes: float64(2), object(8)
memory usage: 33.1+ KB