In [ ]:
print("hello")

hello

In [ ]:
a=10

In [ ]:
print(a)

10

In [ ]:
def myfunc():
  print("Appu")

In [ ]:
myfunc()

Appu

In [ ]:
def add(a,b):
  return a+b

x=5
y=6
print(add(x,y))

11

In [ ]:
for i in range(3,10,2):
  print(i, "Appu")

3 Appu
5 Appu
7 Appu
9 Appu

In [ ]:
for x in range(1, 20, 2):
  print(x)

1
3
5
7
9
11
13
15
17
19

In [ ]:
a=10
if a<20:
  print("A is less than twenty")
else:
  print("a is greater than twenty")

A is less than twenty

In [ ]:
i=0
while(i<10):

  if i%2==0:
    i=i+1
    continue
  print("Appu")
  i=i+1

Appu
Appu
Appu
Appu
Appu

In [ ]:
l=[1,2,3,4,5]
for x in l:
  print(x)

#add
l.append(6)
print(l)

#using index
print(l[0])

#using range of index
print(l[2:5])

#reverse index
print(l[-1])

print(l[-4:-1])

l.insert(1,-1)
print(l)

l.remove(3)
print(l)

x=l.pop(2)
print(l)
print(x)

l.reverse()
print(l)

l.sort()
print(l)

l2=['appu', 'rejish', 'ragavan']
print(l)
print(l2)

l.extend(l2)
print(l)

1
2
3
4
5
[1, 2, 3, 4, 5, 6]
1
[3, 4, 5]
6
[3, 4, 5]
[1, -1, 2, 3, 4, 5, 6]
[1, -1, 2, 4, 5, 6]
[1, -1, 4, 5, 6]
2
[6, 5, 4, -1, 1]
[-1, 1, 4, 5, 6]
[-1, 1, 4, 5, 6]
['appu', 'rejish', 'ragavan']
[-1, 1, 4, 5, 6, 'appu', 'rejish', 'ragavan']

In [ ]:
t=(1,2,3,4,5)
print(t)
print(t[0])

(1, 2, 3, 4, 5)
1

In [ ]:
s={1,2,3,4,5,-1, 0, 6}
print(s)

{0, 1, 2, 3, 4, 5, 6, -1}

In [ ]:
s1={1,2,3,4}
s2={3,4,5,6}

print(s1.union(s2))
print(s1)
print(s2)

print(s1.intersection(s2))

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4}
{3, 4, 5, 6}
{3, 4}

In [ ]:
d={
    "1x":"appu",
    "2":"ragavan",
    "v":[1,2,3,4],
    "t":(5,6,7)
}
#print(d["1x"])
#print(d)

for x in d:
  print(x, d[x])

for x in d.items():
  print(x[0], x[1])

print(d.keys())
print(d.values())

1x appu
2 ragavan
v [1, 2, 3, 4]
t (5, 6, 7)
1x appu
2 ragavan
v [1, 2, 3, 4]
t (5, 6, 7)
dict_keys(['1x', '2', 'v', 't'])
dict_values(['appu', 'ragavan', [1, 2, 3, 4], (5, 6, 7)])

In [ ]:
l=[1,2,3,4,5,6,7,8,9]
lodd=[]
for x in l:
  if x%2==0:
    lodd.append(x)

print(l)
print(lodd)

l2=[x for x in l if x%2==1]
print(l2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 4, 6, 8]
[1, 3, 5, 7, 9]

In [ ]:
def myadd(a, b):
  c=a+b
  return c

x=myadd(5,6)
print(x)

#no return type
#no funciton name
#no blck if the funciton has only one line
#no return statement if one line is the expression that return value

f= lambda a,b: a+b
x=f(5,6)
print(x)

11
11

In [ ]:
f=lambda a:print("Appu", a)
f(5)

Appu 5

In [ ]:
def myfunc(a, b):
  print("a=", a)
  print("b=",b)

myfunc(b="Appu", a="Rejish")

a= Rejish
b= Appu

In [ ]:
def myfunc(*a):
  print(len(a))
  print(a)
  print(a[0])

myfunc(1,2,3,4)

4
(1, 2, 3, 4)
1

In [ ]:
def myfunc(**a):
  print(a)

myfunc(x=2, y=3, z=4)

{'x': 2, 'y': 3, 'z': 4}

In [ ]:
class Student:
  x=5
  def __init__(self):
    self.y=6
    print("I am in init method..")
  def myclassfunc(self):
    print("I am inside class function..")
    print(self.x)
    print(self.y)

a=Student()
a.myclassfunc()

I am in init method..
I am inside class function..
5
6

In [ ]:
class Parent:
  def __init__(self):
    print("I am in parent init method..")

class Child(Parent):
  def __init__(self):
    print("I am in child init method..")
    super().__init__()

c=Child()

I am in child init method..
I am in parent init method..

In [ ]:
#file
f=open("myfile.txt","w")
f.write("Appu ...")
f.close()

In [ ]:
f=open("myfile.txt","a")
f.write("Rejish ...\n")
f.close()

In [ ]:
f=open("myfile.txt","r")
x=f.read()
print(x)
f.close()

Rejish ...Rejish ...Rejish ...Rejish ...

In [ ]:
f=open("myfile.txt","r")
x=f.readline()
print(x)
f.close()

Rejish ...Rejish ...Rejish ...Rejish ...Rejish ...

In [ ]:
f=open("myfile.txt","r")
while True:
    line = f.readline()
    if not line:   # EOF condition
        break
    print(line.strip())
f.close()

Rejish ...Rejish ...Rejish ...Rejish ...Rejish ...
Rejish ...
Rejish ...

In [ ]:
def myfunc1(a,b):
  if a<0:
    raise Exception("Negative value is not allowed..")
  c=a+b;
  return c
def myfunc2(x,y):
  return myfunc1(x,y)

def myfunc3(c,d):
  return myfunc2(c,d)

try:
  x=myfunc3(-2,3)
  print("x=", x)
except Exception as e:
  print("There is some exception", e)
else:
  print("Else part is called...")
finally:
  print("Finally is called..")

There is some exception Negative value is not allowed..
Finally is called..

In [ ]:
name=input("Enter your name:")
print(name)

Enter your name:appu
appu

In [ ]:
import pandas
i={
  "x1":[3,3,3],
  "x2":[6,5,5],
  "x3":[4,5,5],
  "y": [5,4.5, 4.5]
}
print(i)
d=pandas.DataFrame(i)
print(d)
print(d.describe())

{'x1': [3, 3, 3], 'x2': [6, 5, 5], 'x3': [4, 5, 5], 'y': [5, 4.5, 4.5]}
   x1  x2  x3    y
0   3   6   4  5.0
1   3   5   5  4.5
2   3   5   5  4.5
        x1        x2        x3         y
count  3.0  3.000000  3.000000  3.000000
mean   3.0  5.333333  4.666667  4.666667
std    0.0  0.577350  0.577350  0.288675
min    3.0  5.000000  4.000000  4.500000
25%    3.0  5.000000  4.500000  4.500000
50%    3.0  5.000000  5.000000  4.500000
75%    3.0  5.500000  5.000000  4.750000
max    3.0  6.000000  5.000000  5.000000

In [ ]:
dt=pandas.read_csv("test_csv.txt", delimiter='\t')
print(dt)

   x1  x2  x3    y
0   3   6   4  5.0
1   3   5   5  4.5
2   3   5   5  4.5

In [ ]:
import pandas as pd
#Create data frame
#1. python disctionary
d ={
  "a":123,
  "b":345
 }

df=pd.DataFrame(d, index=[0])
print(df)

#2. using list
d1 ={
  "a":[1,2,3,4,5],
  "b":[5,6,7,8,6]
 }
df1=pd.DataFrame(d1)
print(df1)

     a    b
0  123  345
   a  b
0  1  5
1  2  6
2  3  7
3  4  8
4  5  6

In [ ]:
#usign csv file
dt3=pd.read_csv("test_csv.txt", delimiter='\t')
print(dt3)

   x1  x2  x3    y
0   3   6   4  5.0
1   3   5   5  4.5
2   3   5   5  4.5

In [ ]:
#reading json file
dt4=pd.read_json("sample_json.txt")
print(dt4)

                                            students
0  {'id': 1, 'name': 'John Doe', 'age': 20, 'gend...
1  {'id': 2, 'name': 'Mary Smith', 'age': 21, 'ge...
2  {'id': 3, 'name': 'David Lee', 'age': 19, 'gen...

In [ ]:
from ast import Index
dt5=pd.read_excel("test_excel.xlsx")
dt5.index = ['a','b','c','d','e','f','g','h', 'i']
print(dt5)

    id   name  age
a  101  Appu1   21
b  102  Appu2   22
c  103  Appu3   23
d  104  Appu4   24
e  105  Appu5   25
f  106  Appu6   26
g  107  Appu7   27
h  108  Appu8   28
i  109  Appu9   29

In [ ]:
#to get a particualr column
print(dt5[['id', 'name']])

    id   name
a  101  Appu1
b  102  Appu2
c  103  Appu3
d  104  Appu4
e  105  Appu5
f  106  Appu6
g  107  Appu7
h  108  Appu8
i  109  Appu9

In [ ]:
#to get a particualr row
#using index value
print(dt5.iloc[0])

#using row label
print(dt5.loc['a'])

#multiple rows using index
print(dt5.iloc[0:3, 0:2])

#multiple rows using labels
print(dt5.loc['a':'c', "id":"name"])

id        101
name    Appu1
age        21
Name: a, dtype: object
id        101
name    Appu1
age        21
Name: a, dtype: object
    id   name
a  101  Appu1
b  102  Appu2
c  103  Appu3
    id   name
a  101  Appu1
b  102  Appu2
c  103  Appu3

In [ ]:
print(dt5)

    id   name  age
a  101  Appu1   21
b  102  Appu2   22
c  103  Appu3   23
d  104  Appu4   24
e  105  Appu5   25
f  106  Appu6   26
g  107  Appu7   27
h  108  Appu8   28
i  109  Appu9   29

In [ ]:
dt6=dt5.drop('e', inplace=True)
print(dt5)
print(dt6)

    id   name  age
a  101  Appu1   21
b  102  Appu2   22
c  103  Appu3   23
d  104  Appu4   24
f  106  Appu6   26
g  107  Appu7   27
h  108  Appu8   28
i  109  Appu9   29
None

In [ ]:
dt6=dt5[[True, False, True, False,True, False, True, False]]
print(dt6)

    id   name  age
a  101  Appu1   21
c  103  Appu3   23
f  106  Appu6   26
h  108  Appu8   28

In [ ]:
print(dt5['id']==102)

a    False
b     True
c    False
d    False
f    False
g    False
h    False
i    False
Name: id, dtype: bool

In [ ]:
dt5[[True, True, False, False, False, False,False, False]]

    id   name  age
a  101  Appu1   21
b  102  Appu2   22

In [ ]:
print(dt5[dt5['id']==102])

    id   name  age
b  102  Appu2   22

In [ ]:
print(dt5[dt5['id']==102]['name'])

b    Appu2
Name: name, dtype: object

In [ ]:
print(dt5)

    id   name  age
a  101  Appu1   21
b  102  Appu2   22
c  103  Appu3   23
d  104  Appu4   24
f  106  Appu6   26
g  107  Appu7   27
h  108  Appu8   28
i  109  Appu9   29

In [ ]:
print(dt5)

    id   name  age
a  101  Appu1   21
b  102  Appu2   22
c  103  Appu3   23
d  104  Appu4   24
f  106  Appu6   26
g  107  Appu7   27
h  108  Appu8   28
i  109  Appu9   29

In [ ]:
import pandas as pd
s=pd.Series([1,2,3,4], index=['a','b','c','d'])
print(s)2print(s['a'])

a    1
b    2
c    3
d    4
dtype: int64
1

In [ ]:
#1,2,3
#4,5,6
#7,8,9

df=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
print(df)

s1=pd.Series([1,2,3])
s2=pd.Series([4,5,6])
s3=pd.Series([7,8,9])

print(s1, s2, s3)

df1=pd.DataFrame([s1,s2,s3])
print(df1)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
0    1
1    2
2    3
dtype: int64 0    4
1    5
2    6
dtype: int64 0    7
1    8
2    9
dtype: int64
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
s1=pd.Series([1,2,3])
df=pd.DataFrame([s1, s2], index=['a','b'])
print(df)
print(df.index)

df=pd.DataFrame({'a':s1, 'b':s2}, index=[1,2])
print(df)

   0  1  2
a  1  2  3
b  4  5  6
Index(['a', 'b'], dtype='object')
   a  b
1  2  5
2  3  6

In [ ]:
df=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
print(df)
temp=df.values
print(temp)
print(df.index)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
RangeIndex(start=0, stop=3, step=1)

In [ ]:
print(df.shape)

(3, 3)

In [ ]:
print(df.columns)

RangeIndex(start=0, stop=3, step=1)

In [ ]:
print(df.head())

print(df.tail())

print(df.describe())

print(df.info())

   a  b
1  2  5
2  3  6
   a  b
1  2  5
2  3  6
              a         b
count  2.000000  2.000000
mean   2.500000  5.500000
std    0.707107  0.707107
min    2.000000  5.000000
25%    2.250000  5.250000
50%    2.500000  5.500000
75%    2.750000  5.750000
max    3.000000  6.000000
<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 1 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       2 non-null      int64
 1   b       2 non-null      int64
dtypes: int64(2)
memory usage: 48.0 bytes
None

In [ ]:
df=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [11,12,13], [14,15,16], [17,18,19]])
print(df.head(2))
print(df.tail(2))

   0  1  2
0  1  2  3
1  4  5  6
    0   1   2
4  14  15  16
5  17  18  19

In [ ]:
print(df[[True, True, True, False, False, False]])

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [11,12,13], [14,15,16], [17,18,19]])
print(df)

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  11  12  13
4  14  15  16
5  17  18  19

In [ ]:
#first column all rows
print(df[[0]])

#multiple columns
print(df[[0,1]])

#first row
print(df.iloc[0])

#multiple row
print(df.iloc[0:2])

    0
0   1
1   4
2   7
3  11
4  14
5  17
    0   1
0   1   2
1   4   5
2   7   8
3  11  12
4  14  15
5  17  18
0    1
1    2
2    3
Name: 0, dtype: int64
   0  1  2
0  1  2  3
1  4  5  6
   0  1  2
0  1  2  3
1  4  5  6

In [ ]:
print(df.loc[:])

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  11  12  13
4  14  15  16
5  17  18  19

In [ ]:
print(df.iloc[:])

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  11  12  13
4  14  15  16
5  17  18  19

In [ ]:
df=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [11,12,13], [14,15,16], [17,18,19]], index=[2,3,4,5,6,7])
print(df)

    0   1   2
2   1   2   3
3   4   5   6
4   7   8   9
5  11  12  13
6  14  15  16
7  17  18  19

In [ ]:
print(df[[True, False,True, False,True, False]])

    0   1   2
2   1   2   3
4   7   8   9
6  14  15  16

In [ ]:
print(df[0]>4)

2    False
3    False
4     True
5     True
6     True
7     True
Name: 0, dtype: bool

In [ ]:
print(df[df[0]>4])

    0   1   2
4   7   8   9
5  11  12  13
6  14  15  16
7  17  18  19

In [ ]:
df[0:5:2]

KeyError: (slice(0, 5, 2), 0)

In [ ]:
import pandas as pd

df1=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
df2=pd.DataFrame([[11,12,13], [14,15,16], [17,18,19]], columns=[2,3,4], index=[2,3,4])

print(df1)
print(df2)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
    2   3   4
2  11  12  13
3  14  15  16
4  17  18  19

In [ ]:
df1+df2

    0   1   2
0  12  14  16
1  18  20  22
2  24  26  28

In [ ]:
df1+3

    0   1   2
0   4   5   6
1   7   8   9
2  10  11  12

In [ ]:
df1.join(df2, lsuffix="_left", rsuffix="_right", how="outer")

     0    1  2_left  2_right     3     4
0  1.0  2.0     3.0      NaN   NaN   NaN
1  4.0  5.0     6.0      NaN   NaN   NaN
2  7.0  8.0     9.0     11.0  12.0  13.0
3  NaN  NaN     NaN     14.0  15.0  16.0
4  NaN  NaN     NaN     17.0  18.0  19.0

In [ ]:
import pandas as pd

df1=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
print(df1)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df1.to_csv("sample.csv")

In [ ]:
df1.to_excel("sample1.xlsx")

In [ ]:
df1.to_json("sample2.json")

In [ ]:
!pip install pyperclip

Requirement already satisfied: pyperclip in /usr/local/lib/python3.12/dist-packages (1.11.0)

In [ ]:
df2=pd.read_csv("test1.csv", index_col=0)
df2

      Appu    salem   12345678
a
b  Ragavan  vellore  988676786
c   Rasika    erode  897867777

In [ ]:
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df1.to_pickle("sample3.pkl")

In [47]:
import pandas as pd

df3=pd.DataFrame([[1,5,3], [4,2,6], [7,3,9]])
print(df3)

   0  1  2
0  1  5  3
1  4  2  6
2  7  3  9

In [ ]:
def myfunc():
  dsf
print(df3[0].mean())
df.apply()

4.0

In [50]:
df3.sort_values(by=1, key=lambda v: v%2)

   0  1  2
1  4  2  6
0  1  5  3
2  7  3  9

In [53]:
def myfunc1():
  print("I am inside function1..")

def myfunc(f):
  print("I am inside function..")
  f()

#myfunc(myfunc1)

a=myfunc1

a()

I am inside function1..

In [56]:
def sort(l):
  for i in range(len(l)):
    for j in range(len(l)-1):
      if l[j]>l[j+1]:
        temp=l[j]
        l[j]=l[j+1]
        l[j+1]=temp

l1=[5,3,7,2,8,4,9]
print(l1)
sort(l1)
print(l1)

[5, 3, 7, 2, 8, 4, 9]
[2, 3, 4, 5, 7, 8, 9]

In [8]:
class Student:
  def __init__(self, id, age):
    self.id=id
    self.age=age

def sort(l, compFun): #compFunc 0- equal,
  #-1 left bigger than right, 1 = left is smaller than right
  '''
  compFun takes two argument(o1, o2) and its hould compare two values
  return >0 if o1<o2
  return 0 if o1==o2
  return <0 if o1>o2
  '''
  for i in range(len(l)):
    for j in range(len(l)-1):
      if compFun(l[j],l[j+1])<0:
        temp=l[j]
        l[j]=l[j+1]
        l[j+1]=temp

def myComFun(s1, s2):
  if s1.age==s2.age:
    return 0
  elif s1.age > s2.age:
    return -1
  else:
    return 1

def myCompFunc1(s1, s2):
  return s2.age-s1.age

f1=myCompFunc1
f2=lambda s1, s2: s2.age-s1.age

s1=Student(101, 21)
s2=Student(102, 22)
s3=Student(103, 20)
s4=Student(104, 24)
s5=Student(105, 23)

l1=[s2, s1, s5, s3, s4]
print("Before sort..")
for i in range(len(l1)):
  print(l1[i].id, l1[i].age)

print("after sort...")
sort(l1, myCompFunc1)
for i in range(len(l1)):
  print(l1[i].id, l1[i].age)

print("after sort2...")
sort(l1, lambda s1, s2: s2.age-s1.age)
for i in range(len(l1)):
  print(l1[i].id, l1[i].age)

Before sort..
102 22
101 21
105 23
103 20
104 24
after sort...
103 20
101 21
102 22
105 23
104 24
after sort2...
103 20
101 21
102 22
105 23
104 24

In [16]:
import pandas as pd
import numpy as np

N=5

df = pd.DataFrame({
   'A': pd.date_range(start='2016-01-01',periods=N,freq='D'),
   'x': np.linspace(0,stop=N-1,num=N),
   'y': np.random.rand(N),
   'C': np.random.choice(['Low','Medium','High'],N).tolist(),
   'D': np.random.normal(100, 10, size=(N)).tolist()
})

print("Original DataFrame:\n", df)
df_reindexed = df.reindex(index=[0,2,5], columns=['A', 'C', 'B'])

print("\nOutput Reindexed DataFrame:\n",df_reindexed)

Original DataFrame:
            A    x         y       C          D
0 2016-01-01  0.0  0.340707  Medium  80.583612
1 2016-01-02  1.0  0.397708    High  92.036744
2 2016-01-03  2.0  0.037096    High  91.007720
3 2016-01-04  3.0  0.150475    High  95.579781
4 2016-01-05  4.0  0.840374    High  88.910002

Output Reindexed DataFrame:
            A       C   B
0 2016-01-01  Medium NaN
2 2016-01-03    High NaN
5        NaT     NaN NaN

In [29]:
import pandas as pd

df3=pd.DataFrame([[1,5,3], [4,2,6], [7,3,9]], index=['a','b','c'], columns=['c1', 'c2', 'c3'])
print(df3)

for x in df3.items():
  print(x)

   c1  c2  c3
a   1   5   3
b   4   2   6
c   7   3   9
('c1', a    1
b    4
c    7
Name: c1, dtype: int64)
('c2', a    5
b    2
c    3
Name: c2, dtype: int64)
('c3', a    3
b    6
c    9
Name: c3, dtype: int64)

In [25]:
l=[1,2,3,4,5]
for i in range(len(l)):
  print(l[i])

print("Iterating list..")
for x in l:
  print(x)

print("Iterating tuple..")
t=(1,2,3,4,5,6)
for x in t:
  print(x)

print("Iterating set..")
s={1,2,3,4,5,6}
for x in s:
  print(x)

print("Iterating dict..")
d={'a':2, 'b':5, 'c':7}
for x in d.items():
  print(x)

1
2
3
4
5
Iterating list..
1
2
3
4
5
Iterating tuple..
1
2
3
4
5
6
Iterating set..
1
2
3
4
5
6
Iterating dict..
('a', 2)
('b', 5)
('c', 7)

In [31]:
a=(1,2,3)
print(type(a))
b=a
print(type(b))
x,y,z=a
print(type(x), x)
print(type(y), y)
print(type(z), z)

<class 'tuple'>
<class 'tuple'>
<class 'int'> 1
<class 'int'> 2
<class 'int'> 3

In [32]:
import pandas as pd

df3=pd.DataFrame([[1,5,3], [4,2,6], [7,3,9]], index=['a','b','c'], columns=['c1', 'c2', 'c3'])
print(df3)

   c1  c2  c3
a   1   5   3
b   4   2   6
c   7   3   9

In [37]:
#looping dataframe in column wise
for x,y in df3.items():
  print(x)
  print(y)
  print("type of x: ", type(x))
  print("type of y: ", type(y))

  break

c1
a    1
b    4
c    7
Name: c1, dtype: int64
type of x:  <class 'str'>
type of y:  <class 'pandas.core.series.Series'>

In [39]:
#looping dataframe in row wise
for x,y in df3.iterrows():
  print(x)
  print(y)
  print("type of x: ", type(x))
  print("type of y: ", type(y))

  break

a
c1    1
c2    5
c3    3
Name: a, dtype: int64
type of x:  <class 'str'>
type of y:  <class 'pandas.core.series.Series'>

In [52]:
#looping dataframe in row wise
for x in df3.itertuples(index=False, name='Student'):
  print(x)
  #print(type(x))
  #print(x)
  #print(y)
  #print("type of x: ", type(x))
  #print("type of y: ", type(y))

  #break

Student(c1=1, c2=5, c3=3)
Student(c1=4, c2=2, c3=6)
Student(c1=7, c2=3, c3=9)

In [60]:
df7=pd.DataFrame([[101, "Appu", 23], [102, "Ragav", 18], [103, "Rasika", 15]], columns=["id", "name", "age"])
print(df7)
print("")
for x in df7.iterrows():
  #print(x)
  print(x[1]['name'])
  #break

    id    name  age
0  101    Appu   23
1  102   Ragav   18
2  103  Rasika   15

Appu
Ragav
Rasika

In [69]:
class Student:
  def __init__(self, id, name, age) -> None:
    self.id=id
    self.name=name
    self.age=age

s1=Student(101, "Appu", 23)
s2=Student(102, "Ragav", 18)
s3=Student(103, "Rasika", 15)

l1=[s1, s2, s3]
for x in l1:
  print(x.id, x.name, x.age)

print("")
df8=pd.DataFrame([[101, "Appu", 23], [102, "Ragav", 18], [103, "Rasika", 15]], columns=["id", "name", "age"])
print(df8)

print("")
for x in df8.iterrows():
  print(x[1]['id'], x[1]['name'], x[1]['age'])

print("")
for x in df8.itertuples(name="Student"):
  print(x.id, x.name, x.age)

101 Appu 23
102 Ragav 18
103 Rasika 15

    id    name  age
0  101    Appu   23
1  102   Ragav   18
2  103  Rasika   15

101 Appu 23
102 Ragav 18
103 Rasika 15

101 Appu 23
102 Ragav 18
103 Rasika 15

In [71]:
str1 = "appu"
str2 = "ragavan"

str3=str1+str2
print(str3)

appuragavan

In [78]:
df7=pd.DataFrame([[101, "Appu", 23], [102, "Ragav", 18], [103, "Rasika", 15]], columns=["id", "name", "age"])
df8=pd.DataFrame([[104, "Appu1", 23], [105, "Ragav1", 18], [106, "Rasika1", 15]], columns=["id", "name", "age"])
df9=pd.concat([df7,df8], keys=['x','y'], ignore_index=True, axis=1)
print(df9)

     0       1   2    3        4   5
0  101    Appu  23  104    Appu1  23
1  102   Ragav  18  105   Ragav1  18
2  103  Rasika  15  106  Rasika1  15

In [4]:
df7=pd.DataFrame([[101, "Appu", 23], [102, "Ragav", 18], [103, "Rasika", 15]], columns=["id", "name", "age"])
print(df7)

NameError: name 'pd' is not defined

In [83]:
df7[['id', 'age']].pct_change()*100

         id        age
0       NaN        NaN
1  0.990099 -21.739130
2  0.980392 -16.666667

In [85]:
df7['id'].cov(df7['age'])

np.float64(-4.0)

In [86]:
df7['id'].corr(df7['age'])

np.float64(-0.989743318610787)

In [87]:
df7['age'].sort_values()

2    15
1    18
0    23
Name: age, dtype: int64

In [88]:
df7['age'].rank()

0    3.0
1    2.0
2    1.0
Name: age, dtype: float64

In [101]:
ss=pd.Series([1,4,7,1,3,9,5])
ss[ss.rank(method='dense')<=2]

0    1
3    1
4    3
dtype: int64

In [104]:
df7[['id','age']].mean()

id     102.000000
age     18.666667
dtype: float64

In [105]:
df7[['id','age']].median()

id     102.0
age     18.0
dtype: float64

In [106]:
df7[['id','age']].mode()

    id  age
0  101   15
1  102   18
2  103   23

In [107]:
df7[['id','age']].cumsum()

    id  age
0  101   23
1  203   41
2  306   56

In [108]:
df7[['id','age']].cummin()

    id  age
0  101   23
1  101   18
2  101   15

In [109]:
df7[['id','age']].cummax()

    id  age
0  101   23
1  102   23
2  103   23

In [111]:
df1=pd.DataFrame([[True, False, True], [True, False, True]], columns=['c1','c2','c3'])
df1.all()

c1     True
c2    False
c3     True
dtype: bool

In [113]:
df1=pd.DataFrame([[True, False, True], [True, True, True]], columns=['c1','c2','c3'])
df1.any()

c1    True
c2    True
c3    True
dtype: bool

In [114]:
df7[['id','age']].diff()

    id  age
0  NaN  NaN
1  1.0 -5.0
2  1.0 -3.0

In [115]:
df7[['id','age']].max()

id     103
age     23
dtype: int64

In [116]:
df7[['id','age']].idxmax()

id     2
age    0
dtype: int64

In [6]:
import pandas as pd

#get records with max values
df7=pd.DataFrame([[101, "Appu", 23], [102, "Ragav", 18], [103, "Rasika", 15]], columns=["id", "name", "age"])
print(df7)

    id    name  age
0  101    Appu   23
1  102   Ragav   18
2  103  Rasika   15

In [8]:
df7.iloc[df7[['id','age']].idxmax()]

    id    name  age
2  103  Rasika   15
0  101    Appu   23

In [9]:
df7

    id    name  age
0  101    Appu   23
1  102   Ragav   18
2  103  Rasika   15

In [12]:
df7['age'].unique()

array([23, 18, 15])

In [13]:
df7.describe()

          id        age
count    3.0   3.000000
mean   102.0  18.666667
std      1.0   4.041452
min    101.0  15.000000
25%    101.5  16.500000
50%    102.0  18.000000
75%    102.5  20.500000
max    103.0  23.000000

In [11]:
df7['age'].value_counts()

age
23    1
18    1
15    1
Name: count, dtype: int64

In [16]:
df7['name'].str.lower()

0      appu
1     ragav
2    rasika
Name: name, dtype: object

In [22]:
def myfunc(v):
  if type(v)==int:
    return v+1
  if v=='Appu':
    return 1
  elif v=='Ragav':
    return 2
  else:
    return 3

df8=df7.map(myfunc)
print(df7)
print("")
print(df8)

    id    name  age
0  101    Appu   23
1  102   Ragav   18
2  103  Rasika   15

    id  name  age
0  102     1   24
1  103     2   19
2  104     3   16

In [23]:
df7

    id    name  age
0  101    Appu   23
1  102   Ragav   18
2  103  Rasika   15

In [40]:

def mysum(arg:pd.Series, a:int):
  total=20
  for x in arg.index:
    total+=arg[x]
  return total

df7[['id','age']].apply(mysum, axis=1, args=(20,))

0    144
1    140
2    138
dtype: int64

In [35]:
df7[['id','age']]

    id  age
0  101   23
1  102   18
2  103   15

In [36]:
def addone(x):
  return x+1

def multwo(x):
  return x*2

df8=df7[['id','age']].map(addone)
df9=df8.map(multwo)
print(df9)

    id  age
0  204   48
1  206   38
2  208   32

In [37]:
df10=df7[['id','age']].pipe(addone).pipe(multwo)
print(df10)

    id  age
0  204   48
1  206   38
2  208   32

In [53]:
df1=pd.DataFrame([[1,2,3],[4,5,2],[7,8,4],[1,2,2],[4,5,3],[7,8,1],[1,2,1],[4,5,2],[7,8,3]], columns=['reqs','c2','secs'])
#print(df1)

df1['time'] = pd.to_datetime(df1['secs'], unit='s')
df1=df1.sort_values('time')
df1 = df1.set_index('time')

print(df1)
result = df1[['reqs','c2']].rolling('3s').sum()
print(result)

                     reqs  c2  secs
time
1970-01-01 00:00:01     7   8     1
1970-01-01 00:00:01     1   2     1
1970-01-01 00:00:02     4   5     2
1970-01-01 00:00:02     1   2     2
1970-01-01 00:00:02     4   5     2
1970-01-01 00:00:03     1   2     3
1970-01-01 00:00:03     4   5     3
1970-01-01 00:00:03     7   8     3
1970-01-01 00:00:04     7   8     4
                     reqs    c2
time
1970-01-01 00:00:01   7.0   8.0
1970-01-01 00:00:01   8.0  10.0
1970-01-01 00:00:02  12.0  15.0
1970-01-01 00:00:02  13.0  17.0
1970-01-01 00:00:02  17.0  22.0
1970-01-01 00:00:03  18.0  24.0
1970-01-01 00:00:03  22.0  29.0
1970-01-01 00:00:03  29.0  37.0
1970-01-01 00:00:04  28.0  35.0

In [44]:
df1.rolling(window=3).sum()

     c1    c2    c3
0   NaN   NaN   NaN
1   NaN   NaN   NaN
2  12.0  15.0  18.0
3  12.0  15.0  18.0
4  12.0  15.0  18.0
5  12.0  15.0  18.0
6  12.0  15.0  18.0
7  12.0  15.0  18.0
8  12.0  15.0  18.0

In [56]:
df1.sum(axis=1)

time
1970-01-01 00:00:01    16
1970-01-01 00:00:01     4
1970-01-01 00:00:02    11
1970-01-01 00:00:02     5
1970-01-01 00:00:02    11
1970-01-01 00:00:03     6
1970-01-01 00:00:03    12
1970-01-01 00:00:03    18
1970-01-01 00:00:04    19
dtype: int64

In [63]:
df1.agg(func={'reqs':['mean', 'max'], 'c2':['sum'], 'secs':['max']}, axis=0)

      reqs    c2  secs
mean   4.0   NaN   NaN
max    7.0   NaN   4.0
sum    NaN  45.0   NaN

In [72]:
df1.agg(['sum', 'mean','max','min'], axis='index')

      reqs    c2       secs
sum   36.0  45.0  21.000000
mean   4.0   5.0   2.333333
max    7.0   8.0   4.000000
min    1.0   2.0   1.000000

In [70]:
df1.agg(x=('reqs','mean'), y=('reqs','max'), a=('c2','sum'),
        b=('secs','max'), axis='columns')

KeyError: "Column(s) ['c2', 'reqs', 'secs'] do not exist"

In [67]:
df1

                     reqs  c2  secs
time
1970-01-01 00:00:01     7   8     1
1970-01-01 00:00:01     1   2     1
1970-01-01 00:00:02     4   5     2
1970-01-01 00:00:02     1   2     2
1970-01-01 00:00:02     4   5     2
1970-01-01 00:00:03     1   2     3
1970-01-01 00:00:03     4   5     3
1970-01-01 00:00:03     7   8     3
1970-01-01 00:00:04     7   8     4

In [81]:
df1=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['c1','c2','c3'])
df2=pd.DataFrame([[1,2,3],[4,15,16],[17,18,19]], columns=['c1','c2','c3'])
print(df1)
print(df2)

   c1  c2  c3
0   1   2   3
1   4   5   6
2   7   8   9
   c1  c2  c3
0   1   2   3
1   4  15  16
2  17  18  19

In [82]:
df1.merge(df2)

   c1  c2  c3
0   1   2   3

In [86]:
df1.merge(df2, on='c1', how='outer')

   c1  c2_x  c3_x  c2_y  c3_y
0   1   2.0   3.0   2.0   3.0
1   4   5.0   6.0  15.0  16.0
2   7   8.0   9.0   NaN   NaN
3  17   NaN   NaN  18.0  19.0

In [88]:
df1.join(df2, on='c1', lsuffix="_temp")

   c1_temp  c2_temp  c3_temp   c1    c2    c3
0        1        2        3  4.0  15.0  16.0
1        4        5        6  NaN   NaN   NaN
2        7        8        9  NaN   NaN   NaN

In [91]:
df1, df2

(   c1  c2  c3
 0   1   2   3
 1   4   5   6
 2   7   8   9,
    c1  c2  c3
 0   1   2   3
 1   4  15  16
 2  17  18  19)

In [97]:
df1.index=['a','b','c']
df2.index=['a','x','z']

In [100]:
pd.concat([df1, df2], axis=0, join='outer')

   c1  c2  c3
a   1   2   3
b   4   5   6
c   7   8   9
a   1   2   3
x   4  15  16
z  17  18  19

In [102]:
df1.merge(df2, on='c1')

   c1  c2_x  c3_x  c2_y  c3_y
0   1     2     3     2     3
1   4     5     6    15    16

In [105]:
df1.join(df2, lsuffix='_temp', how='outer')

   c1_temp  c2_temp  c3_temp    c1    c2    c3
a      1.0      2.0      3.0   1.0   2.0   3.0
b      4.0      5.0      6.0   NaN   NaN   NaN
c      7.0      8.0      9.0   NaN   NaN   NaN
x      NaN      NaN      NaN   4.0  15.0  16.0
z      NaN      NaN      NaN  17.0  18.0  19.0

In [118]:

mindex=pd.MultiIndex.from_arrays([['a','a','b','b'], [1,2,1,2]],
                                 names=["alpha", "numeric"])
df=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]],
                columns=['c1','c2','c3'],
                index=mindex)
df

               c1  c2  c3
alpha numeric
a     1         1   2   3
      2         4   5   6
b     1         7   8   9
      2        10  11  12

In [121]:
mindex=pd.MultiIndex.from_tuples([('a',1), ('a',2),
                        ('b',1), ('b',2)],
                                 names=["alpha", "numeric"])
df=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]],
                columns=['c1','c2','c3'],
                index=mindex)
df

               c1  c2  c3
alpha numeric
a     1         1   2   3
      2         4   5   6
b     1         7   8   9
      2        10  11  12

In [126]:
l1=[1,2,3,4,5]
l2=['a','b','c','d','e']
l3=list(zip(l1,l2))
print(l3)

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]

In [129]:
l1=['a','b']
l2=[1,2]
mindex=pd.MultiIndex.from_product([l1, l2])
df=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]],
                columns=['c1','c2','c3'],
                index=mindex)
df

     c1  c2  c3
a 1   1   2   3
  2   4   5   6
b 1   7   8   9
  2  10  11  12

In [135]:
indexdf=pd.DataFrame([['a',1],['a',2], ['b',1], ['b',2] ])
mindex=pd.MultiIndex.from_frame(indexdf, names=["alpha", "numeric"])
df=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]],
                columns=['c1','c2','c3'],
                index=mindex)
df

               c1  c2  c3
alpha numeric
a     1         1   2   3
      2         4   5   6
b     1         7   8   9
      2        10  11  12

In [138]:
df.loc[('a',1)]

c1    1
c2    2
c3    3
Name: (a, 1), dtype: int64

In [140]:
df.iloc[0:3]

               c1  c2  c3
alpha numeric
a     1         1   2   3
      2         4   5   6
b     1         7   8   9

In [142]:
df<3

                  c1     c2     c3
alpha numeric
a     1         True   True  False
      2        False  False  False
b     1        False  False  False
      2        False  False  False

In [143]:
df.lt(3)

                  c1     c2     c3
alpha numeric
a     1         True   True  False
      2        False  False  False
b     1        False  False  False
      2        False  False  False

In [4]:
import pandas as pd

df1=pd.DataFrame([[1,2],[3,4]])
df2=pd.DataFrame([[1,4],[7,8]])
print(df1)
print(df2)
print(df1<df2)
print(df1.lt(df2))

   0  1
0  1  2
1  3  4
   0  1
0  1  4
1  7  8
       0     1
0  False  True
1   True  True
       0     1
0  False  True
1   True  True

In [5]:
df1.loc[[True,False]]

   0  1
0  1  2

In [11]:
b=df1<3
b

       0      1
0   True   True
1  False  False

In [15]:
df1

   0  1
0  1  2
1  3  4

In [16]:
df1[b[0]]

   0  1
0  1  2

In [20]:
df1.iloc[b.values,0]

0    1
0    1
Name: 0, dtype: int64

In [21]:
s = pd.Series(["a", "b", "c", "a"], dtype="category")
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): ['a', 'b', 'c']

In [24]:
df = pd.DataFrame({"Col_a": list("aeeioou"), "Col_b": range(7)})
df['Col_a'] = df["Col_a"].astype("category")
print(df.dtypes)
print(df)

Col_a    category
Col_b       int64
dtype: object
  Col_a  Col_b
0     a      0
1     e      1
2     e      2
3     i      3
4     o      4
5     o      5
6     u      6

In [27]:
df = pd.DataFrame({"Col_a": list("aeeioou"), "Col_b": range(7)})
cat=pd.CategoricalDtype(categories=list("aieuo"), ordered=True)
df['Col_a'] = df["Col_a"].astype(cat)
print(df.dtypes)
print(df)

Col_a    category
Col_b       int64
dtype: object
  Col_a  Col_b
0     a      0
1     e      1
2     e      2
3     i      3
4     o      4
5     o      5
6     u      6

In [28]:
df.sort_values('Col_a')

  Col_a  Col_b
0     a      0
3     i      3
1     e      1
2     e      2
6     u      6
4     o      4
5     o      5

In [12]:
import pandas as pd

df=pd.DataFrame([[101,"Appu", "Male","Good"],
                 [102,"Raika", "Female", "Better"],
                 [103,"Ragavan", "Male","Poor"],
                 [104,"Priya", "Female", "Best"]], columns=["id", "name", "sex", "performance"])

df = df.astype({
    'id': 'int',
    'name': 'string',
    'sex': pd.CategoricalDtype(categories=['Male', 'Female'], ordered=True),
    'performance':pd.CategoricalDtype(categories=['Poor', 'Good', 'Better', 'Best'], ordered=True)
})

In [4]:
df.dtypes

id                      int64
name           string[python]
sex                  category
performance          category
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           4 non-null      int64
 1   name         4 non-null      string
 2   sex          4 non-null      category
 3   performance  4 non-null      category
dtypes: category(2), int64(1), string(1)
memory usage: 532.0 bytes

In [6]:
df.sort_values('performance')

    id     name     sex performance
3  104    Priya  Female        Best
1  102    Raika  Female      Better
0  101     Appu    Male        Good
2  103  Ragavan    Male        Poor

In [10]:
df['sex']<'Female'

0     True
1    False
2     True
3    False
Name: sex, dtype: bool

In [14]:
df[df['performance']<'Better']

    id     name   sex performance
0  101     Appu  Male        Good
2  103  Ragavan  Male        Poor

In [16]:
df['performance'].describe()

count        4
unique       4
top       Poor
freq         1
Name: performance, dtype: object

In [18]:
df.max()

/tmp/ipykernel_5980/1151452817.py:1: FutureWarning: <class 'pandas.core.arrays.string_.StringArray'>._reduce will require a `keepdims` parameter in the future
  df.max()

id                104
name            Raika
sex            Female
performance      Best
dtype: object

In [20]:
df['performance']=df['performance'].cat.reorder_categories(new_categories=['Poor', 'Better', 'Good', 'Best'], ordered=True)

In [35]:
df=pd.DataFrame([['a',1],['b',2],['c',1],['d',2]], columns=['col1', 'col2'] )
df=df.astype({'col1':pd.CategoricalDtype(['d','c','b','a']),
              'col2':pd.CategoricalDtype([1,2], ordered=True)})

In [32]:
df.dtypes

col1    category
col2    category
dtype: object

In [36]:
df['col2']<2

0     True
1    False
2     True
3    False
Name: col2, dtype: bool

In [21]:
df.sort_values('performance')

    id     name     sex performance
2  103  Ragavan    Male        Poor
1  102    Raika  Female      Better
0  101     Appu    Male        Good
3  104    Priya  Female        Best

In [53]:
import numpy as np

df=pd.DataFrame([[1,2,3],[4,np.nan,6],[7,8,9]], columns=['c1','c2','c3'])
df

   c1   c2  c3
0   1  2.0   3
1   4  NaN   6
2   7  8.0   9

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      3 non-null      int64
 1   c2      2 non-null      float64
 2   c3      3 non-null      int64
dtypes: float64(1), int64(2)
memory usage: 204.0 bytes

In [44]:
df.isna().sum()

c1    0
c2    1
c3    0
dtype: int64

In [45]:
df.notna()

     c1     c2    c3
0  True   True  True
1  True  False  True
2  True   True  True

In [46]:
df.sum()

c1    12.0
c2    10.0
c3    18.0
dtype: float64

In [47]:
df

   c1   c2  c3
0   1  2.0   3
1   4  NaN   6
2   7  8.0   9

In [52]:
df=df.fillna(df['c2'].mean())
df

   c1   c2  c3
0   1  2.0   3
1   4  5.0   6
2   7  8.0   9

In [54]:
df=df.dropna()

In [55]:
df

   c1   c2  c3
0   1  2.0   3
2   7  8.0   9

In [26]:
import pandas as pd
import numpy as np

df=pd.DataFrame([[False,np.nan,'3'],[False,np.nan,'6'],[False,np.nan,'9']])
df

       0   1  2
0  False NaN  3
1  False NaN  6
2  False NaN  9

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      bool
 1   1       2 non-null      float64
 2   2       3 non-null      object
dtypes: bool(1), float64(1), object(1)
memory usage: 183.0+ bytes

In [27]:
df.isna().sum()

0    0
1    3
2    0
dtype: int64

In [44]:
df1=pd.DataFrame([[1,np.nan],[3,np.nan]])
df1

   0   1
0  1 NaN
1  3 NaN

In [38]:
df2=df1.fillna(0)
df2

   0    1
0  1  0.0
1  3  0.0

In [40]:
df2=df1.fillna(df1.mean(axis=1))
df2

   0    1
0  1  3.0
1  3  3.0

In [43]:
df1=df1.fillna(0)
df1

   0    1
0  1  0.0
1  3  0.0

In [45]:
df1.fillna(0, inplace=True)
df1

   0    1
0  1  0.0
1  3  0.0

In [17]:
df.count()

0    3
1    2
2    3
dtype: int64

In [22]:
df.iloc[:, 1:2].mean()

1    5.0
dtype: float64

In [23]:
df

       0    1  2
0  False  2.0  3
1  False  NaN  6
2  False  8.0  9

In [25]:
df.isna().sum()

0    0
1    1
2    0
dtype: int64

In [46]:
df1=pd.DataFrame([[1,2],[3,np.nan], [5,6]])
df1

   0    1
0  1  2.0
1  3  NaN
2  5  6.0

In [47]:
df2=df1.ffill()
df2

   0    1
0  1  2.0
1  3  2.0
2  5  6.0

In [48]:
df2=df1.bfill()
df2

   0    1
0  1  2.0
1  3  6.0
2  5  6.0

In [51]:
df1=pd.DataFrame([[1,2],[3,np.nan], [5,np.nan],[7,8]])
df1

   0    1
0  1  2.0
1  3  NaN
2  5  NaN
3  7  8.0

In [54]:
df2=df1.ffill(limit=1)
df2

   0    1
0  1  2.0
1  3  2.0
2  5  NaN
3  7  8.0

In [55]:
df1

   0    1
0  1  2.0
1  3  NaN
2  5  NaN
3  7  8.0

In [56]:
df2=df1.replace(3,6)
df2

   0    1
0  1  2.0
1  6  NaN
2  5  NaN
3  7  8.0

In [57]:
df1

   0    1
0  1  2.0
1  3  NaN
2  5  NaN
3  7  8.0

In [58]:
df2=df1.interpolate()
df2

   0    1
0  1  2.0
1  3  4.0
2  5  6.0
3  7  8.0

In [61]:
df2=df1.dropna()
df2

   0    1
0  1  2.0
3  7  8.0

In [62]:
df2=df1.dropna(axis=1)
df2

   0
0  1
1  3
2  5
3  7

In [67]:
df2=df1.dropna(thresh=2, axis=1)
df2

   0    1
0  1  2.0
1  3  NaN
2  5  NaN
3  7  8.0

In [70]:
df1.loc[4]=[np.nan, np.nan]
df1

     0    1
0  1.0  2.0
1  3.0  NaN
2  5.0  NaN
3  7.0  8.0
4  NaN  NaN

In [72]:
df2=df1.dropna(how='all')
df2

     0    1
0  1.0  2.0
1  3.0  NaN
2  5.0  NaN
3  7.0  8.0

In [75]:
df2=df1.dropna(subset=[0])
df2

     0    1
0  1.0  2.0
1  3.0  NaN
2  5.0  NaN
3  7.0  8.0

In [79]:
df1=pd.DataFrame([[1,np.nan],[3,4]], columns=['c1', 'c2'])
df2=pd.DataFrame([[5,6],[np.nan,8]], columns=['c1', 'c2'])
print(df1)
print(df2)
print(df1+df2)

   c1   c2
0   1  NaN
1   3  4.0
    c1  c2
0  5.0   6
1  NaN   8
    c1    c2
0  6.0   NaN
1  NaN  12.0

In [2]:
#is there any duplicate
#drop duplicate rows
import pandas as pd

df=pd.DataFrame([[1,2,3],[4,5,6],[1,2,3]])
df

   0  1  2
0  1  2  3
1  4  5  6
2  1  2  3

In [4]:
df.loc[df.duplicated()]

   0  1  2
2  1  2  3

In [8]:
df=pd.DataFrame([[1,2,1],[4,5,4],[7,8,7]])
df[0]==df[2]

0    True
1    True
2    True
dtype: bool

In [7]:
df.duplicated()

TypeError: DataFrame.duplicated() got an unexpected keyword argument 'axis'

In [13]:
df=pd.DataFrame([[1,2,3],[4,5,6],[1,2,3]])
df.duplicated(keep=False)

0     True
1    False
2     True
dtype: bool

In [17]:
df=pd.DataFrame([[1,2,3],[4,5,6],[1,2,9]])
print(df)
df.duplicated(subset=[0,1])

   0  1  2
0  1  2  3
1  4  5  6
2  1  2  9

0    False
1    False
2     True
dtype: bool

In [22]:
df=pd.DataFrame([[1,2,3],[4,5,6],[1,2,3]])
print(df)
df.drop_duplicates(keep=False,inplace=True)
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  1  2  3
   0  1  2
1  4  5  6

In [24]:
df=pd.DataFrame([[1,2,3],[4,5,6],[1,2,9]])
print(df)
df.drop_duplicates(subset=[0,1])

   0  1  2
0  1  2  3
1  4  5  6
2  1  2  9

   0  1  2
0  1  2  3
1  4  5  6

In [35]:
#1. number of unique values
#2. unique value counts
#3. unique
df=pd.DataFrame([[1,2,3],[4,5,6],[1,2,9]], columns=['c1','c2','c3'])
print(df)
print("")
print(df.nunique())
print("")
#select distinct column_name from table
print(pd.unique(df['c1']))

   c1  c2  c3
0   1   2   3
1   4   5   6
2   1   2   9

c1    2
c2    2
c3    3
dtype: int64

[1 4]
c1  c2  c3
1   2   3     1
        9     1
4   5   6     1
Name: count, dtype: int64

In [38]:
df=pd.DataFrame([[1,2,3],[4,5,6],[1,2,9]], columns=['c1','c2','c3'])
print(df)
print("")
print(df.value_counts(subset=['c1','c2']))

   c1  c2  c3
0   1   2   3
1   4   5   6
2   1   2   9

c1  c2
1   2     2
4   5     1
Name: count, dtype: int64

In [43]:
df1=pd.DataFrame([[1,2,3],[4,5,6],[1,2,9]], columns=['c1','c2','c3'])
print(df1)
print("")

df2=pd.DataFrame([[11,12,13],[14,15,16],[11,12,19]], columns=['c1','c2','c3'])
print(df2)
print("")

df3=pd.concat([df1, df2])
print(df3)

   c1  c2  c3
0   1   2   3
1   4   5   6
2   1   2   9

   c1  c2  c3
0  11  12  13
1  14  15  16
2  11  12  19

   c1  c2  c3
0   1   2   3
1   4   5   6
2   1   2   9
0  11  12  13
1  14  15  16
2  11  12  19

In [45]:
df3.index.duplicated()

array([False, False, False,  True,  True,  True])

In [47]:
df3['c']
df3.columns.duplicated()

array([False, False, False])

In [51]:
df1=pd.DataFrame([[1,2,3],[4,5,6],[1,2,9]], columns=['c1','c2','c3'])
print(df1)
print("")

df2=pd.DataFrame([[11,12,13],[14,15,16],[11,12,19]], columns=['c1','c2','c3'])
print(df2)
print("")

df3=pd.concat([df1, df2], axis=1)
print(df3)
print(df3.columns.duplicated())

   c1  c2  c3
0   1   2   3
1   4   5   6
2   1   2   9

   c1  c2  c3
0  11  12  13
1  14  15  16
2  11  12  19

   c1  c2  c3  c1  c2  c3
0   1   2   3  11  12  13
1   4   5   6  14  15  16
2   1   2   9  11  12  19
[False False False  True  True  True]

In [52]:
#print dataframe with duplicate columns labels
#1. lis the coumns
#2. find the duplicate columsn
#3. print the subset from the DF

   c1  c2  c3  c1  c2  c3
0   1   2   3  11  12  13
1   4   5   6  14  15  16
2   1   2   9  11  12  19

In [59]:
print(df3.columns)
print(df3.columns.duplicated())
print(df3.columns[df3.columns.duplicated()])
print(df3.loc[:,df3.columns.duplicated()])

Index(['c1', 'c2', 'c3', 'c1', 'c2', 'c3'], dtype='object')
[False False False  True  True  True]
Index(['c1', 'c2', 'c3'], dtype='object')
   c1  c2  c3
0  11  12  13
1  14  15  16
2  11  12  19

In [60]:
#sql
#select column, count(*) from table group by column
df1=pd.DataFrame([[1,2,3],[4,5,6],[1,2,9]], columns=['c1','c2','c3'])
print(df1)
print("")

   c1  c2  c3
0   1   2   3
1   4   5   6
2   1   2   9

In [64]:
df1.groupby('c1').groups.get(1)

Index([0, 2], dtype='int64')

In [71]:
df1.groupby('c1').filter(lambda x: x['c2'].sum()>4)

   c1  c2  c3
1   4   5   6

In [66]:
df1.groupby('c1').mean()

     c2   c3
c1
1   2.0  6.0
4   5.0  6.0

In [78]:
from sklearn.datasets import load_breast_cancer
#from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import StandardScaler

# load the dataset
data = load_breast_cancer()
type(data.data)
df=pd.DataFrame(data.data)
#df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       569 non-null    float64
 1   1       569 non-null    float64
 2   2       569 non-null    float64
 3   3       569 non-null    float64
 4   4       569 non-null    float64
 5   5       569 non-null    float64
 6   6       569 non-null    float64
 7   7       569 non-null    float64
 8   8       569 non-null    float64
 9   9       569 non-null    float64
 10  10      569 non-null    float64
 11  11      569 non-null    float64
 12  12      569 non-null    float64
 13  13      569 non-null    float64
 14  14      569 non-null    float64
 15  15      569 non-null    float64
 16  16      569 non-null    float64
 17  17      569 non-null    float64
 18  18      569 non-null    float64
 19  19      569 non-null    float64
 20  20      569 non-null    float64
 21  21      569 non-null    float64
 22  22      569 non-null    float64
 23  23      569 non-null    float64
 24  24      569 non-null    float64
 25  25      569 non-null    float64
 26  26      569 non-null    float64
 27  27      569 non-null    float64
 28  28      569 non-null    float64
 29  29      569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [79]:
df.columns

RangeIndex(start=0, stop=30, step=1)

In [85]:
print(df.duplicated().value_counts())
print(df.duplicated().nunique())
print(df.duplicated().unique())

False    569
Name: count, dtype: int64
1
[False]

In [89]:
from sklearn.datasets import load_iris
data = load_iris()
type(data.data)
df=pd.DataFrame(data.data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [92]:
df.describe()

                0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [93]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}